/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as MetiersRouteImport } from './routes/metiers'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CartePhysiqueRouteImport } from './routes/carte-physique'
import { Route as BuilderiaRouteImport } from './routes/builderia'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetiersIndexRouteImport } from './routes/metiers/index'
import { Route as InscriptionIndexRouteImport } from './routes/inscription.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BuilderiaIndexRouteImport } from './routes/builderia/index'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as MetiersCoachRouteImport } from './routes/metiers/coach'
import { Route as MetiersSlugRouteImport } from './routes/metiers/$slug'
import { Route as InscriptionSelectionDePlanRouteImport } from './routes/inscription.selection-de-plan'
import { Route as InscriptionCartePhysiqueRouteImport } from './routes/inscription.carte-physique'
import { Route as DashboardThemeRouteImport } from './routes/dashboard/theme'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardStyleRouteImport } from './routes/dashboard/style'
import { Route as DashboardStatistiquesRouteImport } from './routes/dashboard/statistiques'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardModelesRouteImport } from './routes/dashboard/modeles'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardLinksRouteImport } from './routes/dashboard/links'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardHelpRouteImport } from './routes/dashboard/help'
import { Route as DashboardContentRouteImport } from './routes/dashboard/content'
import { Route as DashboardContactsRouteImport } from './routes/dashboard/contacts'
import { Route as DashboardCarteRouteImport } from './routes/dashboard/carte'
import { Route as DashboardCardRouteImport } from './routes/dashboard/card'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as BuilderiaResultatRouteImport } from './routes/builderia/resultat'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as InscriptionOffrePlanRouteImport } from './routes/inscription.offre.$plan'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersRoute = MetiersRouteImport.update({
  id: '/metiers',
  path: '/metiers',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CartePhysiqueRoute = CartePhysiqueRouteImport.update({
  id: '/carte-physique',
  path: '/carte-physique',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderiaRoute = BuilderiaRouteImport.update({
  id: '/builderia',
  path: '/builderia',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersIndexRoute = MetiersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MetiersRoute,
} as any)
const InscriptionIndexRoute = InscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InscriptionRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BuilderiaIndexRoute = BuilderiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderiaRoute,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MetiersCoachRoute = MetiersCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => MetiersRoute,
} as any)
const MetiersSlugRoute = MetiersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MetiersRoute,
} as any)
const InscriptionSelectionDePlanRoute =
  InscriptionSelectionDePlanRouteImport.update({
    id: '/selection-de-plan',
    path: '/selection-de-plan',
    getParentRoute: () => InscriptionRoute,
  } as any)
const InscriptionCartePhysiqueRoute =
  InscriptionCartePhysiqueRouteImport.update({
    id: '/carte-physique',
    path: '/carte-physique',
    getParentRoute: () => InscriptionRoute,
  } as any)
const DashboardThemeRoute = DashboardThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStyleRoute = DashboardStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatistiquesRoute = DashboardStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelesRoute = DashboardModelesRouteImport.update({
  id: '/modeles',
  path: '/modeles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarteRoute = DashboardCarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCardRoute = DashboardCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const BuilderiaResultatRoute = BuilderiaResultatRouteImport.update({
  id: '/resultat',
  path: '/resultat',
  getParentRoute: () => BuilderiaRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionOffrePlanRoute = InscriptionOffrePlanRouteImport.update({
  id: '/offre/$plan',
  path: '/offre/$plan',
  getParentRoute: () => InscriptionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/bienvenue': typeof BienvenueRoute
  '/builder': typeof BuilderRoute
  '/builderia': typeof BuilderiaRouteWithChildren
  '/carte-physique': typeof CartePhysiqueRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inscription': typeof InscriptionRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRouteWithChildren
  '/offres': typeof OffresRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builderia/resultat': typeof BuilderiaResultatRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/carte': typeof DashboardCarteRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/modeles': typeof DashboardModelesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/inscription/carte-physique': typeof InscriptionCartePhysiqueRoute
  '/inscription/selection-de-plan': typeof InscriptionSelectionDePlanRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/metiers/coach': typeof MetiersCoachRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/builderia/': typeof BuilderiaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/inscription/': typeof InscriptionIndexRoute
  '/metiers/': typeof MetiersIndexRoute
  '/inscription/offre/$plan': typeof InscriptionOffrePlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/bienvenue': typeof BienvenueRoute
  '/builder': typeof BuilderRoute
  '/carte-physique': typeof CartePhysiqueRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/offres': typeof OffresRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builderia/resultat': typeof BuilderiaResultatRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/carte': typeof DashboardCarteRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/modeles': typeof DashboardModelesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/inscription/carte-physique': typeof InscriptionCartePhysiqueRoute
  '/inscription/selection-de-plan': typeof InscriptionSelectionDePlanRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/metiers/coach': typeof MetiersCoachRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/builderia': typeof BuilderiaIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/inscription': typeof InscriptionIndexRoute
  '/metiers': typeof MetiersIndexRoute
  '/inscription/offre/$plan': typeof InscriptionOffrePlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/bienvenue': typeof BienvenueRoute
  '/builder': typeof BuilderRoute
  '/builderia': typeof BuilderiaRouteWithChildren
  '/carte-physique': typeof CartePhysiqueRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/inscription': typeof InscriptionRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/metiers': typeof MetiersRouteWithChildren
  '/offres': typeof OffresRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builderia/resultat': typeof BuilderiaResultatRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/carte': typeof DashboardCarteRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/modeles': typeof DashboardModelesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/statistiques': typeof DashboardStatistiquesRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/theme': typeof DashboardThemeRoute
  '/inscription/carte-physique': typeof InscriptionCartePhysiqueRoute
  '/inscription/selection-de-plan': typeof InscriptionSelectionDePlanRoute
  '/metiers/$slug': typeof MetiersSlugRoute
  '/metiers/coach': typeof MetiersCoachRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/builderia/': typeof BuilderiaIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/inscription/': typeof InscriptionIndexRoute
  '/metiers/': typeof MetiersIndexRoute
  '/inscription/offre/$plan': typeof InscriptionOffrePlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/bienvenue'
    | '/builder'
    | '/builderia'
    | '/carte-physique'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/dashboard'
    | '/inscription'
    | '/mentions-legales'
    | '/metiers'
    | '/offres'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/templates'
    | '/unsubscribe'
    | '/auth/callback'
    | '/builderia/resultat'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/card'
    | '/dashboard/carte'
    | '/dashboard/contacts'
    | '/dashboard/content'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/modeles'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/statistiques'
    | '/dashboard/style'
    | '/dashboard/team'
    | '/dashboard/theme'
    | '/inscription/carte-physique'
    | '/inscription/selection-de-plan'
    | '/metiers/$slug'
    | '/metiers/coach'
    | '/preview/$token'
    | '/builderia/'
    | '/dashboard/'
    | '/inscription/'
    | '/metiers/'
    | '/inscription/offre/$plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/bienvenue'
    | '/builder'
    | '/carte-physique'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/mentions-legales'
    | '/offres'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/templates'
    | '/unsubscribe'
    | '/auth/callback'
    | '/builderia/resultat'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/card'
    | '/dashboard/carte'
    | '/dashboard/contacts'
    | '/dashboard/content'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/modeles'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/statistiques'
    | '/dashboard/style'
    | '/dashboard/team'
    | '/dashboard/theme'
    | '/inscription/carte-physique'
    | '/inscription/selection-de-plan'
    | '/metiers/$slug'
    | '/metiers/coach'
    | '/preview/$token'
    | '/builderia'
    | '/dashboard'
    | '/inscription'
    | '/metiers'
    | '/inscription/offre/$plan'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/bienvenue'
    | '/builder'
    | '/builderia'
    | '/carte-physique'
    | '/cgu'
    | '/cgv'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/dashboard'
    | '/inscription'
    | '/mentions-legales'
    | '/metiers'
    | '/offres'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/templates'
    | '/unsubscribe'
    | '/auth/callback'
    | '/builderia/resultat'
    | '/dashboard/account'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/card'
    | '/dashboard/carte'
    | '/dashboard/contacts'
    | '/dashboard/content'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/leads'
    | '/dashboard/links'
    | '/dashboard/media'
    | '/dashboard/modeles'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/statistiques'
    | '/dashboard/style'
    | '/dashboard/team'
    | '/dashboard/theme'
    | '/inscription/carte-physique'
    | '/inscription/selection-de-plan'
    | '/metiers/$slug'
    | '/metiers/coach'
    | '/preview/$token'
    | '/builderia/'
    | '/dashboard/'
    | '/inscription/'
    | '/metiers/'
    | '/inscription/offre/$plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  BienvenueRoute: typeof BienvenueRoute
  BuilderRoute: typeof BuilderRoute
  BuilderiaRoute: typeof BuilderiaRouteWithChildren
  CartePhysiqueRoute: typeof CartePhysiqueRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InscriptionRoute: typeof InscriptionRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MetiersRoute: typeof MetiersRouteWithChildren
  OffresRoute: typeof OffresRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TemplatesRoute: typeof TemplatesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PreviewTokenRoute: typeof PreviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers': {
      id: '/metiers'
      path: '/metiers'
      fullPath: '/metiers'
      preLoaderRoute: typeof MetiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte-physique': {
      id: '/carte-physique'
      path: '/carte-physique'
      fullPath: '/carte-physique'
      preLoaderRoute: typeof CartePhysiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builderia': {
      id: '/builderia'
      path: '/builderia'
      fullPath: '/builderia'
      preLoaderRoute: typeof BuilderiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers/': {
      id: '/metiers/'
      path: '/'
      fullPath: '/metiers/'
      preLoaderRoute: typeof MetiersIndexRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/inscription/': {
      id: '/inscription/'
      path: '/'
      fullPath: '/inscription/'
      preLoaderRoute: typeof InscriptionIndexRouteImport
      parentRoute: typeof InscriptionRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/builderia/': {
      id: '/builderia/'
      path: '/'
      fullPath: '/builderia/'
      preLoaderRoute: typeof BuilderiaIndexRouteImport
      parentRoute: typeof BuilderiaRoute
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metiers/coach': {
      id: '/metiers/coach'
      path: '/coach'
      fullPath: '/metiers/coach'
      preLoaderRoute: typeof MetiersCoachRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/metiers/$slug': {
      id: '/metiers/$slug'
      path: '/$slug'
      fullPath: '/metiers/$slug'
      preLoaderRoute: typeof MetiersSlugRouteImport
      parentRoute: typeof MetiersRoute
    }
    '/inscription/selection-de-plan': {
      id: '/inscription/selection-de-plan'
      path: '/selection-de-plan'
      fullPath: '/inscription/selection-de-plan'
      preLoaderRoute: typeof InscriptionSelectionDePlanRouteImport
      parentRoute: typeof InscriptionRoute
    }
    '/inscription/carte-physique': {
      id: '/inscription/carte-physique'
      path: '/carte-physique'
      fullPath: '/inscription/carte-physique'
      preLoaderRoute: typeof InscriptionCartePhysiqueRouteImport
      parentRoute: typeof InscriptionRoute
    }
    '/dashboard/theme': {
      id: '/dashboard/theme'
      path: '/theme'
      fullPath: '/dashboard/theme'
      preLoaderRoute: typeof DashboardThemeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/style': {
      id: '/dashboard/style'
      path: '/style'
      fullPath: '/dashboard/style'
      preLoaderRoute: typeof DashboardStyleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/statistiques': {
      id: '/dashboard/statistiques'
      path: '/statistiques'
      fullPath: '/dashboard/statistiques'
      preLoaderRoute: typeof DashboardStatistiquesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/modeles': {
      id: '/dashboard/modeles'
      path: '/modeles'
      fullPath: '/dashboard/modeles'
      preLoaderRoute: typeof DashboardModelesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/carte': {
      id: '/dashboard/carte'
      path: '/carte'
      fullPath: '/dashboard/carte'
      preLoaderRoute: typeof DashboardCarteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/card': {
      id: '/dashboard/card'
      path: '/card'
      fullPath: '/dashboard/card'
      preLoaderRoute: typeof DashboardCardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/builderia/resultat': {
      id: '/builderia/resultat'
      path: '/resultat'
      fullPath: '/builderia/resultat'
      preLoaderRoute: typeof BuilderiaResultatRouteImport
      parentRoute: typeof BuilderiaRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription/offre/$plan': {
      id: '/inscription/offre/$plan'
      path: '/offre/$plan'
      fullPath: '/inscription/offre/$plan'
      preLoaderRoute: typeof InscriptionOffrePlanRouteImport
      parentRoute: typeof InscriptionRoute
    }
  }
}

interface BuilderiaRouteChildren {
  BuilderiaResultatRoute: typeof BuilderiaResultatRoute
  BuilderiaIndexRoute: typeof BuilderiaIndexRoute
}

const BuilderiaRouteChildren: BuilderiaRouteChildren = {
  BuilderiaResultatRoute: BuilderiaResultatRoute,
  BuilderiaIndexRoute: BuilderiaIndexRoute,
}

const BuilderiaRouteWithChildren = BuilderiaRoute._addFileChildren(
  BuilderiaRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCardRoute: typeof DashboardCardRoute
  DashboardCarteRoute: typeof DashboardCarteRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardModelesRoute: typeof DashboardModelesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatistiquesRoute: typeof DashboardStatistiquesRoute
  DashboardStyleRoute: typeof DashboardStyleRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardThemeRoute: typeof DashboardThemeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCardRoute: DashboardCardRoute,
  DashboardCarteRoute: DashboardCarteRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardModelesRoute: DashboardModelesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatistiquesRoute: DashboardStatistiquesRoute,
  DashboardStyleRoute: DashboardStyleRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardThemeRoute: DashboardThemeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InscriptionRouteChildren {
  InscriptionCartePhysiqueRoute: typeof InscriptionCartePhysiqueRoute
  InscriptionSelectionDePlanRoute: typeof InscriptionSelectionDePlanRoute
  InscriptionIndexRoute: typeof InscriptionIndexRoute
  InscriptionOffrePlanRoute: typeof InscriptionOffrePlanRoute
}

const InscriptionRouteChildren: InscriptionRouteChildren = {
  InscriptionCartePhysiqueRoute: InscriptionCartePhysiqueRoute,
  InscriptionSelectionDePlanRoute: InscriptionSelectionDePlanRoute,
  InscriptionIndexRoute: InscriptionIndexRoute,
  InscriptionOffrePlanRoute: InscriptionOffrePlanRoute,
}

const InscriptionRouteWithChildren = InscriptionRoute._addFileChildren(
  InscriptionRouteChildren,
)

interface MetiersRouteChildren {
  MetiersSlugRoute: typeof MetiersSlugRoute
  MetiersCoachRoute: typeof MetiersCoachRoute
  MetiersIndexRoute: typeof MetiersIndexRoute
}

const MetiersRouteChildren: MetiersRouteChildren = {
  MetiersSlugRoute: MetiersSlugRoute,
  MetiersCoachRoute: MetiersCoachRoute,
  MetiersIndexRoute: MetiersIndexRoute,
}

const MetiersRouteWithChildren =
  MetiersRoute._addFileChildren(MetiersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  BienvenueRoute: BienvenueRoute,
  BuilderRoute: BuilderRoute,
  BuilderiaRoute: BuilderiaRouteWithChildren,
  CartePhysiqueRoute: CartePhysiqueRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InscriptionRoute: InscriptionRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MetiersRoute: MetiersRouteWithChildren,
  OffresRoute: OffresRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TemplatesRoute: TemplatesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PreviewTokenRoute: PreviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
